source 'https://rubygems.org'

ruby '2.7'

gem 'activerecord', '~> 6.0.2'

# Use mysql as the database for Active Record
gem 'mysql2', '>= 0.5.3'

group :development, :test do
    gem 'simplecov', require: false
    gem 'rspec'
    gem 'rubocop', require: false
end


