require './db/config.rb'


task :environment do
	# Connect to database:
	unless ActiveRecord::Base.connected?
		ActiveRecord::Base.establish_connection(Config.current_db_config)
	end
end

namespace :db do

  desc "Create the database"
  task :create do
    ActiveRecord::Tasks::DatabaseTasks.create(Config.current_db_config)
  end

  desc "Migrate the database"
  task migrate: :environment do
    ActiveRecord::Tasks::DatabaseTasks.migrate
  end

  desc "Drop the database"
  task drop: :environment do
    ActiveRecord::Tasks::DatabaseTasks.drop(Config.current_db_config)
  end

  desc "Reset the database"
  task :reset => [:drop, :create, :migrate]

end
